### ISSUE TITLE
macOS Bug - can't see clipboard clear field

### ISSUE THREAD

**Issue by georgesnow** [mmcguill/Strongbox#91] opened 2019-04-10 13:32 UTC
![Screen Shot 2019-04-10 at 9 31 10 AM](https://user-images.githubusercontent.com/12751441/55882998-7c857b00-5b73-11e9-8b39-8b938530a547.png)

the field for adjusting the auto clear clipboard doesn't display to set the time interval.

**Comment by shad0whawk** [comment] 2019-04-10 23:38
I can confirm this bug...

I can see and adjust the slider on my Strongbox installation when I first start the program and open the Preferences dialog box.  Deselecting/selecting the check box only inactivates/activates it, but it's still visible.  If I select the Auto Fill tab in the dialog box and then go back to the General tab, it's no longer visible--deselecting/selecting the check box doesn't change the fact that it's hidden.  This only seems to be impacted by the Auto Fill tab--all other tabs result in normal behaviour.  If I close Strongbox, restart the application, and open the Preferences dialog box, the slider is visible again.

**Comment by mmcguill** [comment] 2019-04-11 12:09
Got it. Fix on the way shortly...

**Comment by mmcguill** [comment] 2019-04-18 15:54
Should be fixed with 1.7.0

**Closed by mmcguill** 2019-04-18 15:54 UTC
