### ISSUE TITLE
Protect App with a Password

### ISSUE THREAD

**Issue by MichiMunich** [mmcguill/Strongbox#27] opened 2019-01-11 08:06 UTC
A password protection (TouchID/FaceID) for the app would be great to protect the locally stored data or the configurations for the cloud data within Strongbox. With a configurable number of failed attempts to open the app, the local data or configurations will be deleted.

**Comment by mmcguill** [comment] 2019-01-13 19:13
Not sure I fully follow you here @MichiMunich. Do you mean, some kind of immediate request for authentication before even showing the list of Safes/Databases?

**Comment by MichiMunich** [comment] 2019-01-13 19:31
Exactly. It should be a pre authentication, so that without entering a password or TouchID no access to the password databases is possible.

**Comment by milesmcclane** [comment] 2019-01-13 19:33
Yes I agree here

**Comment by milesmcclane** [comment] 2019-01-13 20:40
Would be better if there was the option of a passcode/phrase to open the app then Touch ID for the safe, two factors are better than one.

**Comment by eike-f** [comment] 2019-01-17 13:15
I second this idea. My favourite style would be that I can have the password safe open, but access to actually view it is granted only after one enters a custom PIN.
In this way I don't have to retype my really strong (and hence long) decryption password whenever I need a password but am still protected from someone taking my phone and looking at my passwords.
Ideally the password safe is locked again after three (or so) failed attempts to enter the PIN

**Comment by eike-f** [comment] 2019-01-17 13:40
Oh, I'm sorry,
I read through the thread but actually I meant to second MichiMunich:

Personally I dislike touch and faceid, because people can be forced to touch their finger somewhere and look in a certain direction.

My ideal solution is:
Lets call the password that encrypts the safe "passwordkey".
This is a strong password and hence cumbersome to enter into a smartphone.
Implement a new password for strongbox that can be chosen by the user, let's calll it "appkey".
This will be easier to enter.

Then when I start strongbox I have to open my password safe with the passwordkey.

Now whenever I go back to strongbox, the safe is open (unless the auto-close time is up) but I still have to enter the appkey.
Because I would choose an easy appkey, strongbox would close the safe after 3 attempts to enter the appkey.

I think its appropriate to make an option to replace the appkey with faceid or touchid but it's important for me that I can also choose to use an actual appkey for the reasons in the beginning of this post.

**Comment by georgesnow** [comment] 2019-01-17 13:49
Ok, i get it. I thought maybe thats what you meant. And I have seen other apps that allow for authorizing using your password for the account (or safe in this case), but then give you the option to add passcode/password you could use to unlock for a set time frame. ie until a timer runs out or phone is rebooted. This would be taking it one layer deeper to apply the functionality per safe as well.

**Comment by eike-f** [comment] 2019-01-17 13:55
Oh, again my bad:
I actually only use one safe. And if I used several I would not need the appkey per safe, but only for entering the whole app itself. I have no experience of programming for ios but I guess implementing it for the whole of the app is much easier than for every single safe.

**Comment by milesmcclane** [comment] 2019-01-17 13:57
I meant something akin to standard notes, whereby you Touchface ID to enter the app, then set a code to enter the note, which expires after a user set amount of time.
Then if someone forced you to open your phone with touch/faceID, then subsequently your Strongbox app, they would be presented with a further problem -a random code/phrase. 
Of course this could be your actual safe password, but thats very inconvenient for some. This is a kind of halfway place, and of course could be optional.

Seems silly to have a password safe which is as protected as is possible by keepass, to then have it opened by a simple couple of Touch ID inputs with could be forced. This way could be a picture of security and convenience.

**Comment by CzarlsOnGit** [comment] 2019-01-18 14:40
Hi,
Last iOS 1.20.0 added pin codes feature,
- But I noticed that when Touch ID is enabled, pin codes not working
- I need to dis-enable Touch ID and then SB ask for pin codes,

So it work more like alternative to Touch ID?
Is it possible to make it work like addition to Touch ID?

So after correct Touch ID and Convenience PIN- DB opened
After Touch ID and Duress PIN- fake DB opened (or DB deleted- depend on settings)

BR

**Comment by eike-f** [comment] 2019-01-18 15:52
Its cool that you integrate user requests so fast!
This is nitpicky but would it be possible to choose the length of the delay as a glider for minutes?

**Comment by mmcguill** [comment] 2019-01-19 21:02
Hi @CzarlsOnGit , let me see, I'll look into making it work as both OR and AND with pin codes and touch id... Shouldn't be a major problem.

@eike-f I'll add it to the list...

**Comment by eike-f** [comment] 2019-01-19 22:21
Cool, thanks!
Concerning the PIN locking the app (and even more so the convenience PINs) it would be good if a small number (3? Or if its no big deal, a number chosen by the user) of failed attempts to enter the PIN in question would lock all safes so that the encryption is in place again.
In this case I would choose a really long time for auto lock like 2 hours.

**Comment by eike-f** [comment] 2019-01-20 21:19
Feature request:
Make the autocomplete feature also use the PINs.

**Comment by CzarlsOnGit** [comment] 2019-01-23 16:47
Hi,
Last iOS 1.21.0
Acc.  to change log Touch ID AND PIN should work 
However I found serious security concern:
Yes, I can protect DB with biometrics and PIN, however
If in app settings, I will turn off biometrics check (app not asking to confirm action eg. with biometrics), then only PIN is enough to unlock DB

**Comment by mmcguill** [comment] 2019-01-23 16:59
Hi @CzarlsOnGit, ok, so you would expect that if Touch ID is turned off in phone settings, that the app should then revert back to requesting master credentials, rather than allowing log through PIN alone? 

If so, that sounds like a fair request. I'll get it added into the next release.

**Comment by CzarlsOnGit** [comment] 2019-01-23 17:09
requesting master credentials to change Touch ID or PIN options will be the best IMO

**Comment by mmcguill** [comment] 2019-01-23 17:19
Oh I think I misunderstood you. I thought you meant if biometrics was disabled at the phone level AND the app uses BOTH Biometrics and PIN, then we should revert to master credentials (actually I still think this is a good idea, and will implement in next version.)

Also, allowing Biometric AND/OR PIN is by design. Some people will want Biometric Only, some will want PIN only, and some will want both. I think this is good, and allows people choose their preferred convenience setup.

But what I think you're saying is that we should ask for master credentials even after the safe has been opened? I'm not sure about that tbh. Once the safe is open, all bets are off, whoever has it has full access already to your safe at that point. There doesn't seem to me much value in re-asking for credentials? Maybe other people have strong opinions here?

**Comment by CzarlsOnGit** [comment] 2019-01-23 17:28
1.
> Oh I think I misunderstood you. I thought you meant if biometrics was disabled at the phone level AND the app uses BOTH Biometrics and PIN, then we should revert to master credentials (actually I still think this is a good idea, and will implement in next 

This idea i OK
2.
now in iOS 1.21.0, I like to have an option to open DB with Touch ID AND Pin (like 2FA), but if I turn off Touch ID OR PIN in app settings, then it is possible to open DB only with PIN OR Touch ID, so eg. PIN added to unlock DB will be enough to open DB
When I'm set up Touch ID and PIN, I need to be sure that both will be necessary to open DB

**Comment by mmcguill** [comment] 2019-01-23 17:32
Yes, so if you turn off one of those methods then it won't ask you to use that method. This is by design. If you want to be sure that both are required, then yes, you need to enable both methods. You as the user control the convenience methods required.

Not sure if that answers your question, perhaps I'm misunderstanding something?

**Comment by CzarlsOnGit** [comment] 2019-01-23 17:38
from user point of view, control login methods by setting is ok,
I was thinking more about second security layer

**Comment by mmcguill** [comment] 2019-01-23 18:09
Ok, think I understand, and will address in next release. If user configures BOTH convenience methods and one (somehow, by config etc) becomes unavailable, require master credentials to open.

**Comment by eike-f** [comment] 2019-01-24 12:38
For what it's worth, I'm with @mmcguill on both points here:
1. If I change the permissions from within the safe it's my own responsibility
2. If for whatever reasons convenience options can't be the way I configured them, fall back to master credentials.

**Comment by dbluxo** [comment] 2019-02-01 22:14
@mmcguill Will the data be deleted after a few (configurable) failed attempts?

**Comment by mmcguill** [comment] 2019-02-02 11:01
Hi @dbluxo, this is something I could look at with the addition (or return) of the App Lock screen. It could be that if someone enters the wrong pin 3 times, we could remove (or delete) all databases.

**Comment by mmcguill** [comment] 2019-05-17 16:52
Just FYI, The App Lock is available now with 1.28.0. I'll close this off in a couple of days all going well. I'll create a new Github issue for deleting all databases on 3 incorrect attempts.

**Comment by Mukrosz** [comment] 2019-05-21 03:14
Many thanks for implementing this. It was very much needed and now this is my goto app.

**Comment by eike-fokken** [comment] 2019-05-22 08:09
Cool, thanks a lot!

**Comment by mmcguill** [comment] 2019-05-22 10:30
Thanks for all the input everyone... created #121 to track database deletion on incorrect unlock attempts. Closing this one off. Please open new issues if you have any further requests.

**Closed by mmcguill** 2019-05-22 10:30 UTC
